import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { connect } from "react-redux";
import { bindActionCreators } from "redux";
import * as userActions from "../store/actions/userActions";
import { useState, useEffect } from "react";
import SearchBox from "../components/SearchBox";
import Button from "../components/Button";

const Home: NextPage = ({ users, userActions }: any) => {
  const [searchKey, setSearchKey] = useState<string>("");

  useEffect(() => {
    userActions.getUsers();
  }, []);

  console.log(users);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>YellowPages</h1>

        <div className={styles.searchbar_container}>
          <div className={styles.searchbar_row}>
            <SearchBox searchKey={searchKey} handleOnChange={setSearchKey} />
            <Button>Add</Button>
          </div>
        </div>

        <div className={styles.grid}>
          {Array.isArray(users) &&
            users.length > 0 &&
            users.map((user) => (
              <a href="https://nextjs.org/docs" className={styles.card}>
                <h2>{user.name}</h2>
                <p>{user.email}</p>
                <p>{user.phone}</p>
              </a>
            ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

const mapStateToProps = (state: any) => ({
  users: state.userReducer.users,
});

const mapDispatchToProps = (dispatch: any) => ({
  userActions: bindActionCreators(userActions, dispatch),
});

export default connect(mapStateToProps, mapDispatchToProps)(Home);
